stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/heart.csv
    outs:
    - data/raw/heart.csv
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/heart.csv
    outs:
    - data/processed/train_heart.csv
    - data/processed/test_heart.csv
  