base:
  project: Heart Attack Prediction
  random_state: 42
  target_col: target

data_source:
  s3_source: data_given/heart.csv

load_data:
  raw_dataset_csv: data/raw/heart.csv

split_data:
  train_path: data/processed/train_heart.csv
  test_path: data/processed/test_heart.csv
  test_size: 0.2


estimators:
  ExtraTreeClassifier:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      n_estimators: 10
      max_depth: 3     
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: Extra Tree Classification
  run_name: mlop
  registered_model: ExtraTreeClassifier
  remote_server_url: http://192.168.0.104:5000/
